add-to-group: do better checking

diff --git a/staff/acct/add-to-group b/staff/acct/add-to-group
--- a/staff/acct/add-to-group
+++ b/staff/acct/add-to-group
@@ -1,14 +1,33 @@
 #!/bin/bash
 set -euo pipefail
 
+if [ "$#" -ne 2 ]; then
+    echo "usage: $0 username groupname"
+    exit 1
+fi
+
 NEW_USER="$1"
 LDAP_GROUP="$2"
 
-ldapmodify <<EOF
-dn: cn=$LDAP_GROUP,ou=Group,dc=OCF,dc=Berkeley,dc=EDU
+record="dn: cn=$LDAP_GROUP,ou=Group,dc=OCF,dc=Berkeley,dc=EDU
 changetype: modify
 add: memberUid
 memberUid: $NEW_USER
-EOF
+"
 
-echo "$NEW_USER added to $LDAP_GROUP"
+echo "$record"
+echo "====================="
+read -rp "Add new record? [yN] " choice
+
+if [ "$choice" != "y" ] && [ "$choice" != "yes" ]; then
+    echo "Aborted."
+    exit 0
+fi
+
+ldapadd <<< "$record"
+
+if [ "$?" -eq 0 ]; then
+    echo "$NEW_USER added to $LDAP_GROUP"
+else
+    echo "An error occurred."
+fi
