Add shellcheck pre-commit hook

diff --git a/acct/check b/acct/check
--- a/acct/check
+++ b/acct/check
@@ -13,7 +13,7 @@ wtmp_files='/var/log/wtmp /var/log/wtmp.1'
 login_count=5
 
 usage(){
-  echo "Usage: $(basename $0) USER [login_count]"
+  echo "Usage: $(basename "$0") USER [login_count]"
   echo "USER is the username to look up, must be alphanumeric"
   echo "login_count is the number of logins to display, default is 5"
   echo
@@ -24,7 +24,7 @@ usage(){
 }
 
 # process arguments including basic sanitization and respond if needed
-if [ $# -gt 2 -o $# -eq 0 ]; then
+if [ $# -gt 2 ] || [ $# -eq 0 ]; then
   usage
   exit 1
 elif [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
@@ -34,7 +34,7 @@ else
   user=$(echo "$1" | tr -cd '[:alnum:]')
   if [ -n "$2" ]; then
     login_count=$(echo "$2" | tr -cd '[:digit:]')
-    if [ -z $login_count ]; then
+    if [ -z "$login_count" ]; then
       echo 'Error: Invalid login_count' >&2
       echo
       usage
@@ -44,30 +44,30 @@ else
 fi
 
 # check user entry in passwd database
-getent=$(getent passwd $user)
+getent=$(getent passwd "$user")
 if [ -n "$getent" ]; then
   echo "$getent"
 else
-  echo $user not found >&2
+  echo "$user not found" >&2
   exit 2
 fi
 
 # check if sorried
-shell=$(ldapsearch -x -LLL uid=$user loginshell | grep ^loginShell | cut -d' ' -f2)
-if [ $shell = /opt/share/utils/bin/sorried ]; then
+shell=$(ldapsearch -x -LLL uid="$user" loginshell | grep ^loginShell | cut -d' ' -f2)
+if [ "$shell" = /opt/share/utils/bin/sorried ]; then
   echo "WARNING: Account is disabled" >&2
 fi
 
 # account creation time
-creation_time=$(ldapsearch -x -LLL uid=$user creationTime | grep ^creationTime | cut -d' ' -f2)
+creation_time=$(ldapsearch -x -LLL uid="$user" creationTime | grep ^creationTime | cut -d' ' -f2)
 if [ -n "$creation_time" ]; then
   echo "Created on: $(python3 -c "import dateutil.parser; print(dateutil.parser.parse('${creation_time}').strftime('%Y-%m-%d'))")"
 fi
 
 # check if Kerberos principal exists
-kerberos=$(echo TESTIFEXIST | kinit --password-file=STDIN $user 2>&1)
+kerberos=$(echo TESTIFEXIST | kinit --password-file=STDIN "$user" 2>&1)
 if [ -n "$kerberos" ]; then
-  if [ -n "$(echo "$kerberos" | grep unknown$)" ]; then
+  if echo "$kerberos" | grep -q unknown$; then
     echo "WARNING: Kerberos principal does not exist" >&2
   elif [ "$kerberos" != "kinit: Password incorrect" ]; then
     echo "$kerberos"
@@ -76,15 +76,15 @@ fi
 
 # if on NFS, check if home directory exists
 if mount | grep -qE '^[a-z]+://home\b'; then
-  letter=$(echo $user | cut -c1)
-  letter2=$(echo $user | cut -c1-2)
-  homedir=/home/$letter/$letter2/$user
-  if [ ! -d $homedir ]; then
+  letter=$(echo "$user" | cut -c1)
+  letter2=$(echo "$user" | cut -c1-2)
+  homedir="/home/$letter/$letter2/$user"
+  if [ ! -d "$homedir" ]; then
     echo "WARNING: Home directory does not exist" >&2
   else
     # if home directory exists, check if web directory exists
-    webdir=/services/http/users/$letter/$user
-    if [ ! -d $webdir ]; then
+    webdir="/services/http/users/$letter/$user"
+    if [ ! -d "$webdir" ]; then
       echo "WARNING: Web directory does not exist" >&2
       echo "  You can create web directory by running:"
       echo "    sudo mkdir $webdir"
@@ -94,13 +94,13 @@ if mount | grep -qE '^[a-z]+://home\b'; then
 fi
 
 # check if member of groups other than ocf
-groups=$(groups $user | cut -d " " -f3- | grep -v "^ocf$")
+groups=$(groups "$user" | cut -d " " -f3- | grep -v "^ocf$")
 if [ -n "$groups" ]; then
   echo "Member of group(s): $groups"
 fi
 
 # check if CalLink OID number exists in LDAP
-callinkOid=$(ldapsearch -x -LLL uid=$user callinkOid | grep -i ^callinkOid | cut -d' ' -f2)
+callinkOid=$(ldapsearch -x -LLL uid="$user" callinkOid | grep -i ^callinkOid | cut -d' ' -f2)
 if [ -n "$callinkOid" ]; then
   echo "CalLink OID number: $callinkOid"
   if [ "$callinkOid" != 0 ]; then
@@ -109,10 +109,10 @@ if [ -n "$callinkOid" ]; then
 fi
 
 # check if CalNet UID number exists in LDAP
-calnetuid=$(ldapsearch -x -LLL uid=$user calnetuid | grep -i ^calnetuid | cut -d' ' -f2)
+calnetuid=$(ldapsearch -x -LLL uid="$user" calnetuid | grep -i ^calnetuid | cut -d' ' -f2)
 if [ -n "$calnetuid" ]; then
-  calnetemail=$(ldapsearch -x -LLL -H ldap://nds.berkeley.edu -b dc=berkeley,dc=edu uid=$calnetuid  mail | grep ^mail | cut -d' ' -f2)
-  calnetaffiliations=$(ldapsearch -x -LLL -H ldap://nds.berkeley.edu -b dc=berkeley,dc=edu uid=$calnetuid berkeleyEduAffiliations | grep ^berkeleyEduAffiliations | cut -d' ' -f2- | sed -r 's/(^|$)/\"/g' | sort | tr '\n' ' ' | sed 's/ $//g')
+  calnetemail=$(ldapsearch -x -LLL -H ldap://nds.berkeley.edu -b dc=berkeley,dc=edu uid="$calnetuid" mail | grep ^mail | cut -d' ' -f2)
+  calnetaffiliations=$(ldapsearch -x -LLL -H ldap://nds.berkeley.edu -b dc=berkeley,dc=edu uid="$calnetuid" berkeleyEduAffiliations | grep ^berkeleyEduAffiliations | cut -d' ' -f2- | sed -r 's/(^|$)/\"/g' | sort | tr '\n' ' ' | sed 's/ $//g')
   echo "CalNet UID number: $calnetuid"
   if [ -n "$calnetemail" ]; then
     echo "CalNet email address: $calnetemail"
@@ -145,7 +145,7 @@ echo
 paper view "$user"
 
 # check User_Info entries
-User_Info=$([ -f "$User_Info_file" ] && grep ^$user: "$User_Info_file" | cut -d: -f2-)
+User_Info=$([ -f "$User_Info_file" ] && grep ^"$user": "$User_Info_file" | cut -d: -f2-)
 if [ -n "$User_Info" ]; then
   echo
   echo "User_Info entr(y|ies):"
@@ -155,13 +155,13 @@ if [ -n "$User_Info" ]; then
 fi
 
 # list signatories for group account
-echo 
+echo
 echo "Signatories/Signatory for:"
-signat user $user
-    
+signat user "$user"
+
 
 # check user crontab, probably requires root privileges
-crontab=$(crontab -lu $user 2> /dev/null | sed '/^[ ]*$/d')
+crontab=$(crontab -lu "$user" 2> /dev/null | sed '/^[ ]*$/d')
 if [ -n "$crontab" ]; then
   echo
   echo "Crontab on local machine:"
@@ -172,8 +172,8 @@ fi
 
 
 # check currently running processes in tree format
-ps=$(ps Sfw -u $user 2> /dev/null | grep -Fv "PID TTY")
-fingerl=$(finger -m $user | grep "^On since")
+ps=$(ps Sfw -u "$user" 2> /dev/null | tail -n +2)
+fingerl=$(finger -m "$user" | grep "^On since")
 if [ -n "$fingerl" ] || [ -n "$ps" ]; then
   echo
   echo "Currently running processes on local machine:"
@@ -188,7 +188,7 @@ if [ -n "$fingerl" ] || [ -n "$ps" ]; then
 fi
 
 # check most recent login history
-last=$( (for wtmp_file in $wtmp_files; do last -a $user -f $wtmp_file; done) | egrep -v ' begins|^$' | head -n $login_count | awk '{$1=""; print $0}' | sed 's/^[ ]*//g')
+last=$( (for wtmp_file in $wtmp_files; do last -a "$user" -f "$wtmp_file"; done) | egrep -v ' begins|^$' | head -n "$login_count" | awk '{$1=""; print $0}' | sed 's/^[ ]*//g')
 if [ -n "$last" ]; then
   echo
   echo "Recent login history on local machine:"
diff --git a/staff/acct/sorry/unsorry b/staff/acct/sorry/unsorry
--- a/staff/acct/sorry/unsorry
+++ b/staff/acct/sorry/unsorry
@@ -3,106 +3,93 @@
 #Script for unsorrying OCF user accounts, adapted for ldap/kerberos
 #gfs, 3-24-08
 
-LDAPMODIFY=`which ldapmodify`
-KINIT=`which kinit`
-KDESTROY=`which kdestroy`
+LDAPMODIFY=$(which ldapmodify)
+KINIT=$(which kinit)
+KDESTROY=$(which kdestroy)
 
 defaultshell=/bin/bash
 
 # tests for root
-if [[ `/usr/bin/id -u` -ne 0 ]]
-then echo "You must be root to run this"
-exit 2
+if [[ $(/usr/bin/id -u) -ne 0 ]]; then
+    echo "You must be root to run this"
+    exit 2
 fi
 
 
 #usage block
-if [[ $1 = "" ]]
-then
-echo "Usage: $0 [user to be unsorried]"
-exit 0
+if [[ $1 = "" ]]; then
+    echo "Usage: $0 [user to be unsorried]"
+    exit 0
 fi
 
 sorriedUser=$1
 
-if [ -z "`getent passwd $sorriedUser`" ]; then
-  echo "User $sorriedUser does not exist"
-  exit 3
+if [ -z "$(getent passwd "$sorriedUser")" ]; then
+    echo "User $sorriedUser does not exist"
+    exit 3
 fi
 
-userdir=`ldapsearch -x uid=$sorriedUser | grep homeDirectory | cut -d' ' -f2`
+userdir=$(ldapsearch -x uid="$sorriedUser" | grep homeDirectory | cut -d' ' -f2)
 
 #nohome directory case
-if [[ $userdir == "" ]]
-then echo "Could not find the home directory for user $sorriedUser"
-exit 2
+if [[ $userdir == "" ]]; then
+    echo "Could not find the home directory for user $sorriedUser"
+    exit 2
 fi
 
-if [[ ! -e $userdir/.sorry ]]
-then echo "WARNING: User has no .sorry file"
+if [[ ! -e $userdir/.sorry ]]; then
+    echo "WARNING: User has no .sorry file"
 fi
 
 echo "Please ensure that following attributes in LDAP are UP-TO-DATE."
 echo "  for individuals   : calnetuid,  mail"
 echo "  for student groups: callinkoid, mail"
 echo "Press enter to continue, or Ctrl-C to abort"
-read dummy
+read -r _
 
 rootstaffer="$SUDO_USER"
 
-if [ x"$rootstaffer" = x"root" -o -z $rootstaffer ]
-then
-        echo "The sorry.log is much more useful when it logs who you are"
-        echo "rather than simply 'root'. Please enter your username:"
-        read rootstaffer
+if [ x"$rootstaffer" = x"root" ] || [ -z "$rootstaffer" ]; then
+    echo "The sorry.log is much more useful when it logs who you are"
+    echo "rather than simply 'root'. Please enter your username:"
+    read -r rootstaffer
 fi
 
-echo You are $rootstaffer
+echo "You are $rootstaffer"
 
-$KINIT ${rootstaffer}/admin
+$KINIT "${rootstaffer}/admin"
 if [ $? -ne 0 ]; then
     echo "kinit failed, bailing out!"
     exit 1
 fi
 
-#stealing luns's sed madness from makehttp wrapper
-httpdir=`echo $sorriedUser | sed -e 's%\(\(.\)\)%/services/http/users/\2/\1%'`
-#ftpdir=`echo $sorriedUser | sed -e 's%\(\(.\)\)%/services/ftp/users/\2/\1%'`
-#mysqldir=/services/mysql/data/$sorriedUser
+# stealing luns's sed madness from makehttp wrapper
+httpdir="${sorriedUser//\(\(.\)\)/\/services\/http\/users\/\2/\1}"
 
 echo ""
 echo "Changing user's shell back to normal"
-if [[ -e $userdir/.oldshell ]]
-then
-    shell=`cat $userdir/.oldshell | rev | cut -d/ -f1 | rev`
-    if [[ "$shell" == "tcsh" ]]
-    then
+if [[ -e $userdir/.oldshell ]]; then
+    shell=$(rev "$userdir/.oldshell" | cut -d/ -f1 | rev)
+    if [[ "$shell" == "tcsh" ]]; then
         newshell="/bin/tcsh"
-    elif [[ "$shell" == "zsh" ]]
-    then
+    elif [[ "$shell" == "zsh" ]]; then
         newshell="/bin/zsh"
-    elif [[ "$shell" == "csh" ]]
-    then
+    elif [[ "$shell" == "csh" ]]; then
         newshell="/bin/tcsh"
-    elif [[ "$shell" == "ksh" ]]
-    then
+    elif [[ "$shell" == "ksh" ]]; then
         newshell="/bin/bash"
-    elif [[ "$shell" == "bash" ]]
-    then
+    elif [[ "$shell" == "bash" ]]; then
         newshell="/bin/bash"
     else
         newshell=$defaultshell
     fi
 else
-echo ".oldshell file not found, setting shell to $defaultshell"
-newshell=$defaultshell
+    echo ".oldshell file not found, setting shell to $defaultshell"
+    newshell=$defaultshell
 fi
 
 echo ""
 echo "Restoring ownership of passwd entry"
-
-#echo ""
-#echo "Reenabling SMB account"
 
 $LDAPMODIFY -H ldaps://ldap.ocf.berkeley.edu <<EOF
 dn: uid=$sorriedUser,ou=People,dc=OCF,dc=Berkeley,dc=EDU
@@ -114,56 +101,29 @@ replace: gidNumber
 gidNumber: 1000
 EOF
 
-#-
-#replace: sambaAcctFlags
-#sambaAcctFlags: [U          ]
-
-#restoring permission to 755
-chmod 755 $userdir
-
+# restoring permission to 755
+chmod 755 "$userdir"
 
 echo ""
 echo "Restoring services directory permissions:"
-
-if [[ -d $httpdir ]]
-then chmod 755 $httpdir
+if [[ -d $httpdir ]]; then
+    chmod 755 "$httpdir"
 fi
-
-#if [[ -d $ftpdir ]]
-#then chmod 755 $ftpdir
-#fi
-
-#if [[ -d $mysqldir ]]
-#then chmod 755 $mysqldir
-#fi
-
-#echo "Enabling mail for user"
-#grep -v ^$1\$ /var/mail/etc/sorry > /var/mail/etc/sorry.$$
-#chmod 644 /var/mail/etc/sorry.$$
-#chown root:sys /var/mail/etc/sorry.$$
-#mv /var/mail/etc/sorry.$$ /var/mail/etc/sorry
 
 echo ""
 echo "Removing .sorry and .oldshell files"
 
-rm $userdir/.sorry
-rm $userdir/.oldshell
+rm "$userdir/.sorry"
+rm "$userdir/.oldshell"
 
 echo ""
 echo "Final system check:"
-finger -m $sorriedUser
-ldapsearch -x uid=$sorriedUser
-ls -la $userdir
-ls -ld $httpdir
-#ls -ld $ftpdir
-#ls -ld $mysqldir
+finger -m "$sorriedUser"
+ldapsearch -x uid="$sorriedUser"
+ls -la "$userdir"
+ls -ld "$httpdir"
 
-#echo ""
-#echo ""
-#echo "For immediate mail enabling log in to sandstorm and run"
-#echo "  sudo nscd -i passwd && /etc/postfix/ocfconfig/update-sorried.sh"
-
-echo `/bin/date` + $rootstaffer $sorriedUser >> /opt/acct/sorry.log
+echo "$(/bin/date) + $rootstaffer $sorriedUser" >> /opt/acct/sorry.log
 
 $KDESTROY
 
