Applied @kpengboy's suggestions
1. Changed --silent to --quiet
2. Disable `set -e` at places where error-handling exists
3. Added some more instructions
4. Removed some redundant stuff, but idk if this will blow stuff up

diff --git a/makeservices/easywp b/makeservices/easywp
--- a/makeservices/easywp
+++ b/makeservices/easywp
@@ -57,12 +57,18 @@ fi
 
 # Get SQL password
 echo "Resetting database password..."
+# Do not exit immediately if makemysql fails, as we need to display some error message...
+set +e
 sqlpass=$(makemysql --silent)
 # I don't know if this will work... Just make sure no abnormal exit code first!
 if [ $? -ne 0 ] || [[ -z "$sqlpass" ]]; then
     echo -e "\033[31mError:\033[00m Could not retrieve database password. Run makemysql to see the issue."
     exit 1
 fi
+# Only have the aforementioned behaviour when running makemysql
+# Note also technically if should be below this set statement
+# but set messes up with $? as well...
+set -e
 echo "SQL set up and the password can be found in wp-config.php ..."
 
 # Install WordPress and create config file
