Fix makemysql abnormal exit checks (#173)

diff --git a/makeservices/easywp b/makeservices/easywp
--- a/makeservices/easywp
+++ b/makeservices/easywp
@@ -59,9 +59,8 @@ fi
 echo "Resetting database password..."
 # Do not exit immediately if makemysql fails, as we need to display some error message...
 set +e
-sqlpass=$(makemysql --quiet)
-# I don't know if this will work... Just make sure no abnormal exit code first!
-if [ $? ] || [[ -z "$sqlpass" ]]; then
+# Make sure exit code is normal
+if ! sqlpass=$(makemysql --quiet) || [[ -z "$sqlpass" ]]; then
     echo -e "\\033[31mError:\\033[00m Could not retrieve database password. Run makemysql to see the issue."
     exit 1
 fi
