fix so precommit pass

diff --git a/makeservices/easywp b/makeservices/easywp
--- a/makeservices/easywp
+++ b/makeservices/easywp
@@ -61,8 +61,8 @@ echo "Resetting database password..."
 set +e
 sqlpass=$(makemysql --quiet)
 # I don't know if this will work... Just make sure no abnormal exit code first!
-if [ $? -ne 0 ] || [[ -z "$sqlpass" ]]; then
-    echo -e "\033[31mError:\033[00m Could not retrieve database password. Run makemysql to see the issue."
+if [ $? ] || [[ -z "$sqlpass" ]]; then
+    echo -e "\\033[31mError:\\033[00m Could not retrieve database password. Run makemysql to see the issue."
     exit 1
 fi
 # Only have the aforementioned behaviour when running makemysql
