Fixed a stupid logical mistake and added some stuff in bash scripts; did not run pre commit yet

diff --git a/makeservices/easywp b/makeservices/easywp
--- a/makeservices/easywp
+++ b/makeservices/easywp
@@ -57,9 +57,10 @@ fi
 
 # Get SQL password
 echo "Resetting database password..."
-sqlpass=$(makemysql --unreadable-output --silent)
-if [[ -z "$sqlpass" ]]; then
-    echo -e "\\033[31mError:\\033[00m Could not retrieve database password. Run makemysql to see the issue."
+sqlpass=$(makemysql --silent)
+# I don't know if this will work... Just make sure no abnormal exit code first!
+if [ $? -ne 0 ] || [[ -z "$sqlpass" ]]; then
+    echo -e "\033[31mError:\033[00m Could not retrieve database password. Run makemysql to see the issue."
     exit 1
 fi
 echo "SQL set up and the password can be found in wp-config.php ..."
