Added argument parsing and non-human-friendly output

diff --git a/makeservices/makemysql b/makeservices/makemysql
--- a/makeservices/makemysql
+++ b/makeservices/makemysql
@@ -4,20 +4,47 @@ if [[ "$(hostname)" != "tsunami" && "$(hostname)" != "dev-tsunami" ]]; then
     exit 1
 fi
 
+IGNORE_WP=false
+UNREADABLE_OUTPUT=false
+
+# Parse arguments down below
+while (( "$#" )); do
+    case "$1" in
+        -i|--ignore-wp)
+            IGNORE_WP=true
+            shift
+            ;;
+        -u|--unreadable-output)
+            UNREADABLE_OUTPUT=true
+            shift
+            ;;
+        # I've seen -*|--*=), but idk what does the = serve
+        -*|--*)
+            # Output to stderr
+            echo "Error: Unsupported flag $1" >&2
+            exit 1
+            ;;
+    esac
+done
+
 PASS=$(sudo -u mysql /opt/share/utils/makeservices/makemysql-real | tee /dev/tty | tail -n 1 | grep -Po '(?<=: )([0-9a-zA-Z]){24,}$')
 
 # Check if wp is installed with wp-cli
 # And change password if installed with easywp
 # But change password only if installed with easywp is a wrong statement
 # Use --ignore-wp flag to skip this process
-if (wp core is-installed --quiet --path="$HOME/public_html" > /dev/null 2>&1) &&
-        ([ $# -ne 1 ] || ( [ $# -eq 1 ] && [ ! "$1" = '--ignore-wp' ])); then
+if (wp core is-installed --quiet --path="$HOME/public_html" > /dev/null 2>&1) && ! $IGNORE_WP ; then
     echo "WordPress installation detected, changing WordPress mysql password for you."
     wp config set DB_PASSWORD "$PASS" > /dev/null 2>&1
 fi
-# Added for backward compatibility - the last line will be
-# extracted by "tail -n 1" and the mysterious "grep"
-# will extract the password after the colon
-# So that it simulate the same behaviour as the original makemysql
-# which output the same thing as in makemysql-real
-echo "Your MySQL database password is: $PASS"
+
+if $UNREADABLE_OUTPUT; then
+    echo "$PASS"
+else
+    # Added for backward compatibility - the last line will be
+    # extracted by "tail -n 1" and the mysterious "grep"
+    # will extract the password after the colon in legacy codes
+    # So that it simulate the same behaviour as the original makemysql
+    # which output the same thing as in makemysql-real
+    echo "Your MySQL database password is: $PASS"
+fi
