fix makemysql so that easywp might work (#154)
This commit consists 18 commits in total, earliest one dating back to May 2020, intended to fix chain reactions caused by https://github.com/ocf/utils/pull/129.
This commit:
1. Changed `makemysql-real`, allowing it to output only the password and nothing else if a specific argument is given
2. Changed `makemysql`, allowing it to correctly fetch password printed by `makemysql-real`, allowing it to be silent if no wordpress installation is found, allowing it to not change wordpress password if a specific argument is given, and allowing it to output only the password and nothing else if a specific argument is given.
3. Changed `easywp` so that it is compatible with the updated `makemysql`.
Hopefully, this will not break ocf infra.

18 commits:
* rewrote so that it might work
* idk wat autopep8 changed/suggested i followed its advice
* forgot to add the messages
* Added argument parsing and non-human-friendly output
* Squashed two commits
redirected some stuff to stderr
fix stupid mistakes for makemysql-real
* updated all three scripts so that they support some silent arguments and make things fancy but they might not work as I didn't test it
* fix stupid bugs made in 3cac9d4d
* fix pre-commit problem made in 3cac9d4d
* Wrapper for if silent
* Fixed a stupid logical mistake and added some stuff in bash scripts; did not run pre commit yet
* Applied @kpengboy's suggestions
1. Changed --silent to --quiet
2. Disable `set -e` at places where error-handling exists
3. Added some more instructions
4. Removed some redundant stuff, but idk if this will blow stuff up
* Bug: if quite is specified, do not ask if user wants to proceed.
* Indentation Errors
* Fix, silent should be global variable
* Fixed some bugs in easywp
* fix comment
* fix so precommit pass
* more to squash

diff --git a/makeservices/makemysql b/makeservices/makemysql
--- a/makeservices/makemysql
+++ b/makeservices/makemysql
@@ -4,8 +4,52 @@ if [[ "$(hostname)" != "tsunami" && "$(hostname)" != "dev-tsunami" ]]; then
     exit 1
 fi
 
-PASS=$(sudo -u mysql /opt/share/utils/makeservices/makemysql-real | tee /dev/tty | tail -n 1 | grep -Po '(?<=: )([0-9a-zA-Z]){24,}$')
+IGNORE_WP=false
+QUIET=false
 
-echo 'Changing WordPress database password'
-cd ~/public_html/
-wp config set DB_PASSWORD "$PASS" > /dev/null
+# Parse arguments down below
+while (( "$#" )); do
+    case "$1" in
+        -i|--ignore-wp)
+            IGNORE_WP=true
+            shift
+            ;;
+        -q|--quiet)
+            QUIET=true
+            shift
+            ;;
+        -*)
+            # Output to stderr
+            echo "Error: Unsupported flag $1" >&2
+            exit 1
+            ;;
+    esac
+done
+
+# The correctness of this line relies on the fact that
+# makemysql-real will output the new password ONLY on the
+# last line. The --quiet will also make sure it only output the password...
+PASS=$(sudo -u mysql /opt/share/utils/makeservices/makemysql-real --quiet)
+
+if [ $? ] ; then
+    echo 'makemysql-real did not exit properly.'
+    echo 'Run "sudo -u mysql /opt/share/utils/makeservices/makemysql-real" for a more verbose output.'
+    echo 'Additionally, you may contact staff members for help. This script will stop.'
+    exit 1
+fi
+
+# Check if wp is installed, wp-cli cannot be used as it verifies DB password as well
+# And change password if installed with easywp
+# Use --ignore-wp flag to skip this process
+if ! $IGNORE_WP && [ -f "$HOME/public_html/wp-config.php" ] ; then
+    if ! $QUIET; then
+        echo "WordPress installation detected, changing WordPress mysql password for you."
+    fi
+    wp config set DB_PASSWORD "$PASS" --path="$HOME/public_html" > /dev/null 2>&1
+fi
+
+if $QUIET; then
+    echo "$PASS"
+else
+    echo "Your MySQL database password is: $PASS"
+fi
