pdf-open: don't continue after running evince in error cases

diff --git a/desktop/pdf-open b/desktop/pdf-open
--- a/desktop/pdf-open
+++ b/desktop/pdf-open
@@ -1,10 +1,10 @@
 #!/bin/bash -e
-[ "$#" -ne 1 ] && (echo 'Bad arguments, trying evince...'; exec evince "$@")
-[ -f "$1" ] || (echo 'File does not exist, trying evince...'; exec evince "$@")
+[ "$#" -ne 1 ] && { echo 'Bad arguments, trying evince...'; exec evince "$@"; }
+[ -f "$1" ] || { echo 'File does not exist, trying evince...'; exec evince "$@"; }
 
-size=$(du "$1") || (echo 'Cannot get size, trying evince...'; exec evince "$@")
+size=$(du "$1") || { echo 'Cannot get size, trying evince...'; exec evince "$@"; }
 size=$(cut -f1 <<< "$size")
-[ "$size" -lt 5120 ] || (echo 'Too large, trying evince...'; exec evince "$@")
+[ "$size" -lt 5120 ] || { echo 'Too large, trying evince...'; exec evince "$@"; }
 
 echo 'Rasterizing PDF...'
 tmp=$(mktemp --suffix='.pdf')
